// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ChimeraApi.Data.EF
{
    public partial class ForumPosts
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Guid CreatedById { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public Guid StatusId { get; set; }
        public Guid PostCategoryId { get; set; }
    }
}