// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ChimeraApi.Data.EF
{
    public partial class Users
    {
        public Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public DateTime RegistrationDateTime { get; set; }
        public DateTime LastLoginDateTime { get; set; }
        public Guid UserDataId { get; set; }
        public Guid StatusId { get; set; }
        public string UserName { get; set; }
    }
}