// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ChimeraApi.Data.EF
{
    public partial class UserData
    {
        public Guid Id { get; set; }
        public string Data { get; set; }
    }
}