// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ChimeraApi.Data.EF
{
    public partial class UserRoles
    {
        public Guid UserId { get; set; }
        public Guid RoleId { get; set; }
        public Guid AssignedById { get; set; }
    }
}